const promptTags = [
  { value: 'writing', label: 'Writing' },
  { value: 'journal', label: 'Journal' },
  { value: 'mental health', label: 'Mental Health' },
  { value: 'creative writing', label: 'Creative Writing' },
  { value: 'story', label: 'Story' },
  { value: 'essay', label: 'Essay' },
  { value: 'self-discovery', label: 'Self-Discovery' },
  { value: 'high school', label: 'High School' },
  { value: 'middle school', label: 'Middle School' },
  { value: 'elementary', label: 'Elementary' },
  { value: 'college', label: 'College' },
  { value: 'business', label: 'Business' },
  { value: 'social media', label: 'Social Media' },
  { value: 'resume', label: 'Resume' },
  { value: 'dating', label: 'Dating' },
  { value: 'coding', label: 'Coding' },
  { value: 'fiction', label: 'Fiction' },
  { value: 'non-fiction', label: 'Non-Fiction' },
  { value: 'poetry', label: 'Poetry' },
  { value: 'children', label: 'Children' },
  { value: 'adults', label: 'Adults' },
  { value: 'teens', label: 'Teens' },
  { value: 'self-improvement', label: 'Self-Improvement' },
  { value: 'productivity', label: 'Productivity' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'academic', label: 'Academic' },
  { value: 'research', label: 'Research' },
  { value: 'analysis', label: 'Analysis' },
  { value: 'brainstorming', label: 'Brainstorming' },
  { value: 'summarization', label: 'Summarization' },
]

export { promptTags }
