const promptTags = [
  { value: 'Writing', label: 'Writing' },
  { value: 'Journal', label: 'Journal' },
  { value: 'Mental Health', label: 'Mental Health' },
  { value: 'Creative Writing', label: 'Creative Writing' },
  { value: 'Story', label: 'Story' },
  { value: 'Essay', label: 'Essay' },
  { value: 'Self-Discovery', label: 'Self-Discovery' },
  { value: 'High School', label: 'High School' },
  { value: 'Middle School', label: 'Middle School' },
  { value: 'Elementary', label: 'Elementary' },
  { value: 'College', label: 'College' },
  { value: 'Business', label: 'Business' },
  { value: 'Social Media', label: 'Social Media' },
  { value: 'Resume', label: 'Resume' },
  { value: 'Dating', label: 'Dating' },
  { value: 'Coding', label: 'Coding' },
  { value: 'Fiction', label: 'Fiction' },
  { value: 'Non-Fiction', label: 'Non-Fiction' },
  { value: 'Poetry', label: 'Poetry' },
  { value: 'Children', label: 'Children' },
  { value: 'Adults', label: 'Adults' },
  { value: 'Teens', label: 'Teens' },
  { value: 'Self-Improvement', label: 'Self-Improvement' },
  { value: 'Productivity', label: 'Productivity' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Academic', label: 'Academic' },
  { value: 'Research', label: 'Research' },
  { value: 'Analysis', label: 'Analysis' },
  { value: 'Brainstorming', label: 'Brainstorming' },
  { value: 'Summarization', label: 'Summarization' },
]

export { promptTags }
